# Generated by Django 3.1.4 on 2021-01-29 00:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nano', '0002_newspost_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='avator',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article/%Y%m%d'),
        ),
    ]
