# Generated by Django 3.1.5 on 2021-02-08 01:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nano', '0003_auto_20210129_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='avator',
            field=imagekit.models.fields.ProcessedImageField(upload_to='news/%Y%m%d'),
        ),
    ]
