# Generated by Django 3.1.4 on 2020-12-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labId', models.CharField(max_length=100)),
                ('lab_description', models.CharField(max_length=200)),
            ],
        ),
    ]
