# Generated by Django 3.1.5 on 2021-02-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labId', models.CharField(max_length=100)),
                ('lab_description', models.CharField(max_length=200)),
            ],
        ),
    ]
